### ISSUE TITLE
About ./gen_faster_rcnn_textvqa.sh file

### ISSUE THREAD

**Issue by AzeroGYH** [WYchelsy/DiagNet#9]
Can you provide ./gen_faster_rcnn_textvqa.sh file?  I think it may consist of generate_tsv.py,but generate_tsv.py is run under python2.x,but the project is under python3.x. Thanks for your reply!

**Comment by JasonQSY** [comment]
Sorry for the inconvenience, but the bottom-up-attention is actually a fork of the original BUTD code release. https://github.com/peteanderson80/bottom-up-attention

Hence, to run it, you need a caffe and python2 environment. We recommend you refer to the README. I think the script is just running https://github.com/w-yi/DiagNet/blob/master/bottom-up-attention/tools/generate_tsv.py to generate features in tsv format. Since we want to use pytorch and python3, we wrote https://github.com/w-yi/DiagNet/blob/master/scripts/butd_feature.py to convert features to numpy format.

**Comment by AzeroGYH** [comment]
> Can you provide ./gen_faster_rcnn_textvqa.sh file? I think it may consist of generate_tsv.py,but generate_tsv.py is run under python2.x,but the project is under python3.x. Thanks for your reply!

**Comment by AzeroGYH** [comment]
> > Can you provide ./gen_faster_rcnn_textvqa.sh file? I think it may consist of generate_tsv.py,but generate_tsv.py is run under python2.x,but the project is under python3.x. Thanks for your reply!

**Comment by AzeroGYH** [comment]
> Sorry for the inconvenience, but the bottom-up-attention is actually a fork of the original BUTD code release. https://github.com/peteanderson80/bottom-up-attention
> 
> Hence, to run it, you need a caffe and python2 environment. We recommend you refer to the README. I think the script is just running https://github.com/w-yi/DiagNet/blob/master/bottom-up-attention/tools/generate_tsv.py to generate features in tsv format. Since we want to use pytorch and python3, we wrote https://github.com/w-yi/DiagNet/blob/master/scripts/butd_feature.py to convert features to numpy format.

I get it.Thank you so much.I will close the issue.
